// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvpkwdnfkteaqocdrdqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cGt3ZG5ma3RlYXFvY2RyZHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTM2MzcsImV4cCI6MjA2NTI4OTYzN30.vo6XdENS9wuK0Ar_pHNjd8FLZ4BvDclYmDnVwqawknc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);