// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpxntgiugrqujrsuhrxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJweG50Z2l1Z3JxdWpyc3Vocnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTg4NzQsImV4cCI6MjA2NTk3NDg3NH0.3tBOAgUPNmmsq7IK8pg6i_MnPKv-9J66QuFZd2CbSDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);